// Generated by a tool, do not change manually
// Tool: GenerateLibrary.ps1
// Generated Date: 

using Microsoft.Extensions.Logging;

namespace CommonLoggingLibrary.EventIds
{
  /// <summary>
  /// Catastrophic, unplanned, unrecoverable, unexpected. boom!
  /// </summary>
  public static class Catastrophic
  {
    /// <summary>
    /// 701 Ultimate development shame, this marks the worst that can happen, an exception occurred, wasn&#39;t trapped but the application&#39;s main process caught it.  Used in the raising of Event ID <see cref="Constants.APPLICATION_UNHANDLEDEXCEPTION">701</see>.  To raise this Event, use method <see cref="Application.UnhandledException"/>
    /// </summary>
    public static EventId Application_UnhandledException => new(Constants.APPLICATION_UNHANDLEDEXCEPTION, nameof(Application.ApplicationLoggingExtensions.Application_UnhandledException));
  }
}

