// Generated by a tool, do not change manually
// Tool: GenerateLibrary.ps1
// Generated Date: 

using Microsoft.Extensions.Logging;

namespace CommonLoggingLibrary.EventIds
{
  /// <summary>
  /// Base class for every EventIds
  /// </summary>
  internal class Constants
  {
    /// <summary>101 - Referenced by Declaration <see cref="LowLevel.Application_Starting"/>, raised by method <see cref="Application.Starting"/>
    /// Message: Application is starting.  Args: {args}
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>101</description>
    ///     <description><see cref="APPLICATION_STARTING"/></description>
    ///     <description><see cref="Application.Starting"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>102</description>
    ///     <description><see cref="APPLICATION_STARTED"/></description>
    ///     <description><see cref="Application.Started"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_STARTING = 101;
    /// <summary>102 - Referenced by Declaration <see cref="LowLevel.Application_Started"/>, raised by method <see cref="Application.Started"/>
    /// Message: Application is Started.  Elapsed: {totalMilliseconds} milliseconds
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>101</description>
    ///     <description><see cref="APPLICATION_STARTING"/></description>
    ///     <description><see cref="Application.Starting"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>102</description>
    ///     <description><see cref="APPLICATION_STARTED"/></description>
    ///     <description><see cref="Application.Started"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_STARTED = 102;
    /// <summary>103 - Referenced by Declaration <see cref="LowLevel.Application_Stopping"/>, raised by method <see cref="Application.Stopping"/>
    /// Message: Application is stopping.  Reason: {reason}
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>103</description>
    ///     <description><see cref="APPLICATION_STOPPING"/></description>
    ///     <description><see cref="Application.Stopping"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>104</description>
    ///     <description><see cref="APPLICATION_STOPPED"/></description>
    ///     <description><see cref="Application.Stopped"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_STOPPING = 103;
    /// <summary>104 - Referenced by Declaration <see cref="LowLevel.Application_Stopped"/>, raised by method <see cref="Application.Stopped"/>
    /// Message: Application is Stopped
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>103</description>
    ///     <description><see cref="APPLICATION_STOPPING"/></description>
    ///     <description><see cref="Application.Stopping"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>104</description>
    ///     <description><see cref="APPLICATION_STOPPED"/></description>
    ///     <description><see cref="Application.Stopped"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_STOPPED = 104;
    /// <summary>105 - Referenced by Declaration <see cref="LowLevel.Application_Pausing"/>, raised by method <see cref="Application.Pausing"/>
    /// Message: Application is pausing.  Reason: {reason}
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>105</description>
    ///     <description><see cref="APPLICATION_PAUSING"/></description>
    ///     <description><see cref="Application.Pausing"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>106</description>
    ///     <description><see cref="APPLICATION_PAUSED"/></description>
    ///     <description><see cref="Application.Paused"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_PAUSING = 105;
    /// <summary>106 - Referenced by Declaration <see cref="LowLevel.Application_Paused"/>, raised by method <see cref="Application.Paused"/>
    /// Message: Application is Paused
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>105</description>
    ///     <description><see cref="APPLICATION_PAUSING"/></description>
    ///     <description><see cref="Application.Pausing"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>106</description>
    ///     <description><see cref="APPLICATION_PAUSED"/></description>
    ///     <description><see cref="Application.Paused"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_PAUSED = 106;
    /// <summary>107 - Referenced by Declaration <see cref="LowLevel.Application_Resuming"/>, raised by method <see cref="Application.Resuming"/>
    /// Message: Application is Resuming
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>107</description>
    ///     <description><see cref="APPLICATION_RESUMING"/></description>
    ///     <description><see cref="Application.Resuming"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>108</description>
    ///     <description><see cref="APPLICATION_RESUMED"/></description>
    ///     <description><see cref="Application.Resumed"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_RESUMING = 107;
    /// <summary>108 - Referenced by Declaration <see cref="LowLevel.Application_Resumed"/>, raised by method <see cref="Application.Resumed"/>
    /// Message: Application is Resumed
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>107</description>
    ///     <description><see cref="APPLICATION_RESUMING"/></description>
    ///     <description><see cref="Application.Resuming"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>108</description>
    ///     <description><see cref="APPLICATION_RESUMED"/></description>
    ///     <description><see cref="Application.Resumed"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int APPLICATION_RESUMED = 108;
    /// <summary>109 - Referenced by Declaration <see cref="LowLevel.Configuration_Reading"/>, raised by method <see cref="Configuration.Reading"/>
    /// Message: Reading Configuration
    /// </summary>
    internal const int CONFIGURATION_READING = 109;
    /// <summary>110 - Referenced by Declaration <see cref="LowLevel.Configuration_Validating"/>, raised by method <see cref="Configuration.Validating"/>
    /// Message: Validating Configuration {friendlyName}
    /// </summary>
    internal const int CONFIGURATION_VALIDATING = 110;
    /// <summary>111 - Referenced by Declaration <see cref="LowLevel.Configuration_ValueIsValid"/>, raised by method <see cref="Configuration.ValueIsValid"/>
    /// Message: Configuration value for {friendlyName} is IsValid
    /// </summary>
    internal const int CONFIGURATION_VALUEISVALID = 111;
    /// <summary>112 - Referenced by Declaration <see cref="LowLevel.Configuration_ReadingConnectionString"/>, raised by method <see cref="Configuration.ReadingConnectionString"/>
    /// Message: Reading ConnectionString. name: {name}
    /// </summary>
    internal const int CONFIGURATION_READINGCONNECTIONSTRING = 112;
    /// <summary>113 - Referenced by Declaration <see cref="LowLevel.Configuration_VerifyingConnectionString"/>, raised by method <see cref="Configuration.VerifyingConnectionString"/>
    /// Message: Verifying ConnectionString. name: {name}, connectionString: {connectionString}
    /// </summary>
    internal const int CONFIGURATION_VERIFYINGCONNECTIONSTRING = 113;
    /// <summary>114 - Referenced by Declaration <see cref="LowLevel.Configuration_ConnectionStringIsValid"/>, raised by method <see cref="Configuration.ConnectionStringIsValid"/>
    /// Message: ConnectionString {name} is valid
    /// </summary>
    internal const int CONFIGURATION_CONNECTIONSTRINGISVALID = 114;
    /// <summary>115 - Referenced by Declaration <see cref="LowLevel.Dependency_Loading"/>, raised by method <see cref="Dependency.Loading"/>
    /// Message: Resolving and loading dependencies
    /// </summary>
    internal const int DEPENDENCY_LOADING = 115;
    /// <summary>116 - Referenced by Declaration <see cref="LowLevel.Dependency_Resolved"/>, raised by method <see cref="Dependency.Resolved"/>
    /// Message: All dependencies are resolved
    /// </summary>
    internal const int DEPENDENCY_RESOLVED = 116;
    /// <summary>117 - Referenced by Declaration <see cref="LowLevel.Logging_Initialized"/>, raised by method <see cref="Logging.Initialized"/>
    /// Message: Logging is initialized and switching to the official target(s): {targets}
    /// </summary>
    internal const int LOGGING_INITIALIZED = 117;
    /// <summary>118 - Referenced by Declaration <see cref="LowLevel.Logging_Started"/>, raised by method <see cref="Logging.Started"/>
    /// Message: Logging started
    /// </summary>
    internal const int LOGGING_STARTED = 118;
    /// <summary>119 - Referenced by Declaration <see cref="LowLevel.Logging_Stopped"/>, raised by method <see cref="Logging.Stopped"/>
    /// Message: Logging stopped
    /// </summary>
    internal const int LOGGING_STOPPED = 119;
    /// <summary>201 - Referenced by Declaration <see cref="OperationalInformation.External_ConnectingTo"/>, raised by method <see cref="External.ConnectingTo"/>
    /// Message: Connecting to External. Name: {externalName}, uri {uri}
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>201</description>
    ///     <description><see cref="EXTERNAL_CONNECTINGTO"/></description>
    ///     <description><see cref="External.ConnectingTo"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>202</description>
    ///     <description><see cref="EXTERNAL_CONNECTEDTO"/></description>
    ///     <description><see cref="External.ConnectedTo"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int EXTERNAL_CONNECTINGTO = 201;
    /// <summary>202 - Referenced by Declaration <see cref="OperationalInformation.External_ConnectedTo"/>, raised by method <see cref="External.ConnectedTo"/>
    /// Message: Connecting to External. Name: {externalName}, uri {uri}
    /// This event is part of a pair:
    /// <list type="table">
    ///   <listheader>
    ///     <description>ing/ed</description>
    ///     <description>Event Id</description>
    ///     <description>Name</description>
    ///     <description>Method</description>
    ///   </listheader>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>201</description>
    ///     <description><see cref="EXTERNAL_CONNECTINGTO"/></description>
    ///     <description><see cref="External.ConnectingTo"/></description>
    ///   </item>
    ///   <item>
    ///     <description>Ing</description>
    ///     <description>202</description>
    ///     <description><see cref="EXTERNAL_CONNECTEDTO"/></description>
    ///     <description><see cref="External.ConnectedTo"/></description>
    ///   </item>
    /// </list>
    /// </summary>
    internal const int EXTERNAL_CONNECTEDTO = 202;
    /// <summary>203 - Referenced by Declaration <see cref="OperationalInformation.External_Calling"/>, raised by method <see cref="External.Calling"/>
    /// Message: Calling external {externalName} uri {uri}
    /// </summary>
    internal const int EXTERNAL_CALLING = 203;
    /// <summary>204 - Referenced by Declaration <see cref="OperationalInformation.Application_InNormalMode"/>, raised by method <see cref="Application.InNormalMode"/>
    /// Message: Application is running in Normal Mode
    /// </summary>
    internal const int APPLICATION_INNORMALMODE = 204;
    /// <summary>205 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_Pong"/>, raised by method <see cref="Diagnostics.Pong"/>
    /// Message: Pong
    /// </summary>
    internal const int DIAGNOSTICS_PONG = 205;
    /// <summary>206 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_TraceStarted"/>, raised by method <see cref="Diagnostics.TraceStarted"/>
    /// Message: Trace started. Target: {target}
    /// </summary>
    internal const int DIAGNOSTICS_TRACESTARTED = 206;
    /// <summary>207 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_TraceFinished"/>, raised by method <see cref="Diagnostics.TraceFinished"/>
    /// Message: Trace finished. Target: {target}
    /// </summary>
    internal const int DIAGNOSTICS_TRACEFINISHED = 207;
    /// <summary>208 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_SelfCheckStarted"/>, raised by method <see cref="Diagnostics.SelfCheckStarted"/>
    /// Message: Self-Check started.  Requested by {trigger}
    /// </summary>
    internal const int DIAGNOSTICS_SELFCHECKSTARTED = 208;
    /// <summary>209 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_SelfCheckValid"/>, raised by method <see cref="Diagnostics.SelfCheckValid"/>
    /// Message: Functioning within designed parameters.  Number of tests: {numberOfTests}
    /// </summary>
    internal const int DIAGNOSTICS_SELFCHECKVALID = 209;
    /// <summary>210 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_HealthCheckStarted"/>, raised by method <see cref="Diagnostics.HealthCheckStarted"/>
    /// Message: Health Check Started
    /// </summary>
    internal const int DIAGNOSTICS_HEALTHCHECKSTARTED = 210;
    /// <summary>211 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_HealthCheckIsHealthy"/>, raised by method <see cref="Diagnostics.HealthCheckIsHealthy"/>
    /// Message: Healthy - Number of tests: {numberOfTests}
    /// </summary>
    internal const int DIAGNOSTICS_HEALTHCHECKISHEALTHY = 211;
    /// <summary>212 - Referenced by Declaration <see cref="OperationalInformation.Dependency_ValidatingVersion"/>, raised by method <see cref="Dependency.ValidatingVersion"/>
    /// Message: Validating {friendlyName} version
    /// </summary>
    internal const int DEPENDENCY_VALIDATINGVERSION = 212;
    /// <summary>213 - Referenced by Declaration <see cref="OperationalInformation.Dependency_VersionMatchesExpected"/>, raised by method <see cref="Dependency.VersionMatchesExpected"/>
    /// Message: Good: {friendlyName} version {actualVersion} matches expected version {expectedVersion}
    /// </summary>
    internal const int DEPENDENCY_VERSIONMATCHESEXPECTED = 213;
    /// <summary>301 - Referenced by Declaration <see cref="OperationalWarning.Application_InMaintenance"/>, raised by method <see cref="Application.InMaintenance"/>
    /// Message: Application is in Maintenance mode.
    /// </summary>
    internal const int APPLICATION_INMAINTENANCE = 301;
    /// <summary>302 - Referenced by Declaration <see cref="OperationalWarning.Diagnostics_ValidationFailed"/>, raised by method <see cref="Diagnostics.ValidationFailed"/>
    /// Message: Self-Check found issues.  {issues}
    /// </summary>
    internal const int DIAGNOSTICS_VALIDATIONFAILED = 302;
    /// <summary>303 - Referenced by Declaration <see cref="OperationalWarning.Diagnostics_HealthCheckIsUnhealthy"/>, raised by method <see cref="Diagnostics.HealthCheckIsUnhealthy"/>
    /// Message: Bad health report. Number of failed tests: {numberOfTests}.
    /// </summary>
    internal const int DIAGNOSTICS_HEALTHCHECKISUNHEALTHY = 303;
    /// <summary>304 - Referenced by Declaration <see cref="OperationalWarning.Dependency_VersionMismatch"/>, raised by method <see cref="Dependency.VersionMismatch"/>
    /// Message: Bad: {friendlyName} version {actualVersion} does not match expected version {expectedVersion}, some functionality might not work as expected.
    /// </summary>
    internal const int DEPENDENCY_VERSIONMISMATCH = 304;
    /// <summary>401 - Referenced by Declaration <see cref="RecoverableWarning.Application_InDegradedMode"/>, raised by method <see cref="Application.InDegradedMode"/>
    /// Message: Application is in Degraded mode.  Start throttling incoming connections or scale out/scale up.
    /// </summary>
    internal const int APPLICATION_INDEGRADEDMODE = 401;
    /// <summary>402 - Referenced by Declaration <see cref="RecoverableWarning.Configuration_NotVerifiable"/>, raised by method <see cref="Configuration.NotVerifiable"/>
    /// Message: Configuration is not verifiable.
    /// </summary>
    internal const int CONFIGURATION_NOTVERIFIABLE = 402;
    /// <summary>418 - Referenced by Declaration <see cref="OperationalInformation.Diagnostics_ImaTeapot"/>, raised by method <see cref="Diagnostics.ImaTeapot"/>
    /// Message: Event raised when describing HTCPCP, a protocol for controlling, monitoring, and diagnosing coffee pots.
    /// </summary>
    internal const int DIAGNOSTICS_IMATEAPOT = 418;
    /// <summary>501 - Referenced by Declaration <see cref="UnrecoverableWarning.Configuration_Unusable"/>, raised by method <see cref="Configuration.Unusable"/>
    /// Message: Configuration is Unusable.  Reason {reason}
    /// </summary>
    internal const int CONFIGURATION_UNUSABLE = 501;
    /// <summary>502 - Referenced by Declaration <see cref="UnrecoverableWarning.External_ConnectionFailedAuthentication"/>, raised by method <see cref="External.ConnectionFailedAuthentication"/>
    /// Message: Connection to External {externalName} with {credentials} failed because of an authentication error.  {exception}
    /// </summary>
    internal const int EXTERNAL_CONNECTIONFAILEDAUTHENTICATION = 502;
    /// <summary>503 - Referenced by Declaration <see cref="UnrecoverableWarning.External_ConnectionFailedAuthorization"/>, raised by method <see cref="External.ConnectionFailedAuthorization"/>
    /// Message: Connection to External {externalName} with {credentials} failed because of an authorization error.  {exception}
    /// </summary>
    internal const int EXTERNAL_CONNECTIONFAILEDAUTHORIZATION = 503;
    /// <summary>504 - Referenced by Declaration <see cref="UnrecoverableWarning.Dependency_ResolutionFailed"/>, raised by method <see cref="Dependency.ResolutionFailed"/>
    /// Message: Failed to resolve dependency {friendlyName}
    /// </summary>
    internal const int DEPENDENCY_RESOLUTIONFAILED = 504;
    /// <summary>505 - Referenced by Declaration <see cref="UnrecoverableWarning.External_NotificationNotSent"/>, raised by method <see cref="External.NotificationNotSent"/>
    /// Message: Notification not sent.  Method {method}, Recipient {recipient}
    /// </summary>
    internal const int EXTERNAL_NOTIFICATIONNOTSENT = 505;
    /// <summary>506 - Referenced by Declaration <see cref="UnrecoverableWarning.Configuration_ValueIsInvalid"/>, raised by method <see cref="Configuration.ValueIsInvalid"/>
    /// Message: Configuration setting {friendlyName} with value {value} failed the test {test}.
    /// </summary>
    internal const int CONFIGURATION_VALUEISINVALID = 506;
    /// <summary>601 - Referenced by Declaration <see cref="Exceptional.External_ConnectionFailedTimeout"/>, raised by method <see cref="External.ConnectionFailedTimeout"/>
    /// Message: Connection to External {externalName} using {uri} failed because of a timeout {exception}
    /// </summary>
    internal const int EXTERNAL_CONNECTIONFAILEDTIMEOUT = 601;
    /// <summary>602 - Referenced by Declaration <see cref="Exceptional.External_ConnectionFailedTargetServiceUnavailable"/>, raised by method <see cref="External.ConnectionFailedTargetServiceUnavailable"/>
    /// Message: Connection to External {externalName} using {uri} failed because target is unavailable {exception}
    /// </summary>
    internal const int EXTERNAL_CONNECTIONFAILEDTARGETSERVICEUNAVAILABLE = 602;
    /// <summary>603 - Referenced by Declaration <see cref="Exceptional.Dependency_VersionMismatchedDegradedMode"/>, raised by method <see cref="Dependency.VersionMismatchedDegradedMode"/>
    /// Message: Target {friendlyName} has wrong version {actualVersion}, expected version {expectedVersion}.  Using fallback {fallbackName} {fallbackVersion}, application will continue to work, but in degraded mode
    /// </summary>
    internal const int DEPENDENCY_VERSIONMISMATCHEDDEGRADEDMODE = 603;
    /// <summary>604 - Referenced by Declaration <see cref="Exceptional.Dependency_VersionMismatchedShuttingDown"/>, raised by method <see cref="Dependency.VersionMismatchedShuttingDown"/>
    /// Message: Target {friendlyName} has wrong version {actualVersion}, expected version {expectedVersion}.  Application can&#39;t continue.
    /// </summary>
    internal const int DEPENDENCY_VERSIONMISMATCHEDSHUTTINGDOWN = 604;
    /// <summary>701 - Referenced by Declaration <see cref="Catastrophic.Application_UnhandledException"/>, raised by method <see cref="Application.UnhandledException"/>
    /// Message: Unhandled exception {exception}
    /// </summary>
    internal const int APPLICATION_UNHANDLEDEXCEPTION = 701;
  }
}

