// Generated by a tool, do not change manually
// Tool: GenerateLibrary.ps1
// Generated Date: 

using Microsoft.Extensions.Logging;

namespace CommonLoggingLibrary.EventIds
{
  /// <summary>
  /// Internal, recoverable problems, where the app can continue to work but with limited functionality, like the app is running in DegradedMode, the app has the ability to recover from the incident.  Admin intervention is not a necessity but is a good idea to monitor the situation.
  /// </summary>
  public static class RecoverableWarning
  {
    /// <summary>
    /// 401 The application is running in degraded mode, some functionality might be affected.  Used in the raising of Event ID <see cref="Constants.APPLICATION_INDEGRADEDMODE">401</see>.  To raise this Event, use method <see cref="Application.InDegradedMode"/>
    /// </summary>
    /// <remarks>
    /// <para>Typical outcome of a failed health check.</para>
    /// <para>A great application will have a plan B in the event it finds it can&#39;t do certain actions, inform the IT/Admins and update the UI accordingly so the user aware of the situation but that they&#39;re in good hands and that they don&#39;t have to worry, things will be alright.</para>
    /// <para>An example of a plan B is an external system that suddenly becomes offline, but the app can run with cached values, or will switch to a local storage system until the target system becomes back online.</para>
    /// </remarks>
    public static EventId Application_InDegradedMode => new(Constants.APPLICATION_INDEGRADEDMODE, nameof(Application.ApplicationLoggingExtensions.Application_InDegradedMode));
    /// <summary>
    /// 402 The configuration was loaded, but the content is not verifiable  Used in the raising of Event ID <see cref="Constants.CONFIGURATION_NOTVERIFIABLE">402</see>.  To raise this Event, use method <see cref="Configuration.NotVerifiable"/>
    /// </summary>
    public static EventId Configuration_NotVerifiable => new(Constants.CONFIGURATION_NOTVERIFIABLE, nameof(Configuration.ConfigurationLoggingExtensions.Configuration_NotVerifiable));
  }
}

