// Generated by a tool, do not change manually
// Tool: GenerateLibrary.ps1
// Generated Date: {{DateTime.Now}}

// See https://aka.ms/new-console-template for more information

using CommonLoggingLibrary.Application;
using Microsoft.Extensions.Logging;

var loggerFactory = LoggerFactory.Create(builder => builder.AddSimpleConsole(configure => { configure.SingleLine = true; }));
var Log = loggerFactory.CreateLogger<Program>();

var startedInitializationAt = System.DateTime.UtcNow;
Log.Application_Starting(args);

System.Console.WriteLine("Hello, World!");

System.Threading.Tasks.Task.Delay(1234);

var finishedInitializationAt = System.DateTime.UtcNow;

Log.Application_InNormalMode();
Log.Application_Started((finishedInitializationAt - startedInitializationAt).TotalMilliseconds);